import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Navbar } from "@/components/Navbar/navbar"
import { Footer } from "@/components/Footer/footer"
import Providers from "@/components/Providers"
import { Toaster } from "sonner"
import { SiteFooter } from "@/components/layouts/site-footer"
import { SiteHeader } from "@/components/layouts/site-header"
import { cookies } from "next/headers"
import { getServerSideUser } from "@/lib/payload-utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  const nextCookies = cookies()
  const { user } = await getServerSideUser(nextCookies)

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <SiteHeader user={user} />
            {/* <Navbar title={"AWSHCommerce"} /> */}
            <main className="min-h-[calc(100vh-57px-97px)] flex-1">
              {children}
              {modal}
            </main>
            {/* <Footer /> */}
            <SiteFooter />
          </Providers>
        </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
  )
}
